### ISSUE TITLE
Support JPA mappedBy DOT notation with embeddables

### ISSUE THREAD

**Issue by beikov** [datanucleus/datanucleus-core#137]
As the testcase shows, mapping the inverse relation with *mappedBy* does not work when the relation is in an embeddable. I don't know if it's a bug or JPA does not mandate this, but EclipseLink and Hibernate support it.

[jpa-mapped-by-embeddable.zip](https://github.com/datanucleus/datanucleus-core/files/486973/jpa-mapped-by-embeddable.zip)

**Comment by andyjefferson** [comment]
Core metadata processing now allows the use of DOT notation in "mappedBy" (of 1-N relations). Untested on 1-1
