### ISSUE TITLE
Types of generic MappedSuperClass fail to resolve

### ISSUE THREAD

**Issue by beikov** [datanucleus/datanucleus-core#138]
As the following testcase shows, a generic property type of a mapped superclass can't be resolved properly.
Actually I think there are 2 bugs, but they are closely related.

Note that Hibernate as well as EclipseLink support these mappings.

Sorry for google drive link, but GitHub doesn't seem to be able to detect zip files currently...
https://drive.google.com/open?id=0B6WtHspz6xhvWkloaHh3TXcxMkU

**Comment by beikov** [comment]
Any chance that this will be backported to 4.1?

**Comment by andyjefferson** [comment]
It will when I'm back from holiday ...

**Comment by beikov** [comment]
Great thanks. Enjoy your holiday :)
