### ISSUE TITLE
Enhancement runs into StackOverflowException because of issue in core

### ISSUE THREAD

**Issue by beikov** [datanucleus/datanucleus-core#167]
I haven't had the time yet to debug that, but maybe you can quickly spot the issue.
Here is the stacktrace: 

To reproduce clone the project with `git clone https://github.com/Blazebit/blaze-persistence`.
Then just run `mvn -P "datanucleus-4,h2" -pl core/testsuite -am clean install -DskipTests` and you will run into the problem.

**Comment by andyjefferson** [comment]
You seem to be using datanucleus-core 4.1.14. There is 4.1.15 and 4.1.16. I tried with 4.1.16 and it works. Over the last few weeks I've completed some TODOs in metadata handling in master and some of those have been backported to 4.1 so maybe one of those fixed whatever it was. Suggest that you upgrade core, rdbms and api-jpa jars for 4.x

**Comment by beikov** [comment]
Looks good, thanks for the hint! Would be nice if you could release all artifacts at once then the updating would be easier ^^

**Comment by andyjefferson** [comment]
If finding it hard to keep track of which dependencies to use together you could consider using the Maven artifact

    <dependency>
        <groupId>org.datanucleus</groupId>
        <artifactId>datanucleus-accessplatform-jpa-rdbms</artifactId>
        <version>4.1.16</version>
        <type>pom</type>
    </dependency>

which equates to 

    <dependency>
        <groupId>org.datanucleus</groupId>
        <artifactId>javax.persistence</artifactId>
        <version>2.1.3</version>
        <scope>provided</scope>
    </dependency>
    <dependency>
        <groupId>org.datanucleus</groupId>
        <artifactId>datanucleus-core</artifactId>
        <version>4.1.16</version>
    </dependency>
    <dependency>
        <groupId>org.datanucleus</groupId>
        <artifactId>datanucleus-api-jpa</artifactId>
        <version>4.1.14</version>
    </dependency>
    <dependency>
        <groupId>org.datanucleus</groupId>
        <artifactId>datanucleus-jpa-query</artifactId>
        <version>4.0.6</version>
    </dependency>
    <dependency>
        <groupId>org.datanucleus</groupId>
        <artifactId>datanucleus-rdbms</artifactId>
        <version>4.1.18</version>
    </dependency>
