### ISSUE TITLE
javax.cache can throw exceptions, so should catch and log all

### ISSUE THREAD

**Issue by andyjefferson** [datanucleus/datanucleus-core#168]
If using the default cache all just works since we are using a Map to cache. When swapping to an L2 cache like javax.cache we can get exceptions thrown due to persistable objects not being serializable etc. We should catch and log all exceptions and not rethrow them. This would lead to a much cleaner usage of persistence methods

**Comment by chrisco484** [comment]
This is more of a "how does it do it question?" than an isssue:
I often wonder how the 'reachability' for caching purposes is restricted by DN. Say I have an object that is part of a large object graph and the top level object (which can reach all others via direct or indirect references) is cached how does the cache know to only cache a serialized representation of the single top level object and not end up caching (in its serialized form) the entire object graph. Does DN perform some behind the scenes 'smarts' to transform java object references into OID references prior or during serialization?

**Comment by andyjefferson** [comment]
Also nothing to do with this issue (suggest that you use [Gitter](https://gitter.im/datanucleus/Lobby) or the forum for such questions since they are of no use to anyone else hidden away in an unrelated issue.
 
When you persist an object graph it L2 caches a representation of EVERY object it comes across in that graph, not just some top level object. In the "cached representation" of each object it caches the "id" of any related object (rather than the related field value), as per https://github.com/datanucleus/datanucleus-core/blob/master/src/main/java/org/datanucleus/cache/L2CachePopulateFieldManager.java#L322 . It does no "Java serialization"
