### ISSUE TITLE
Cross join fails with NucleusUserException

### ISSUE THREAD

**Issue by beikov** [datanucleus/datanucleus-core#170]
I don't know where this belongs to, but here you can find the testcase for the issue(Unfortunately GitHub Upload of ZIPs doesn't seem to work): https://drive.google.com/file/d/0B6WtHspz6xhvUFhfbkk3RVB0U1k/view?usp=sharing

The query which uses a cross join fails with the following exception:
org.datanucleus.exceptions.NucleusUserException: Query has reference to member "correlatedDocumentOnlyForId" of class "com.blazebit.persistence.view.testsuite.entity.Document" yet this doesnt exist!

**Comment by andyjefferson** [comment]
Since it is RDBMS specific (i.e CROSS JOIN) then belongs in datanucleus-rdbms. Added as https://github.com/datanucleus/datanucleus-rdbms/issues/159.
