### ISSUE TITLE
Support join on map key

### ISSUE THREAD

**Issue by beikov** [datanucleus/datanucleus-core#182]
Although the JPA spec does not cover this, a join on a KEY() expression should be possible. The following query should work `SELECT a FROM Entity e JOIN e.map m JOIN KEY(m).association a`

**Comment by beikov** [comment]
Here is a testcase showing both join styles. They are supported in EclipseLink and will be in Hibernate in the next major version.
[jpa-join-map-key.zip](https://github.com/datanucleus/datanucleus-core/files/739452/jpa-join-map-key.zip)

**Comment by andyjefferson** [comment]
The syntax quoted makes no sense, largely due to JPQL utterly ignoring the fact that there are 3 things in a Map field ... the Map, the key and the value. 

In the example "m" is not the Map, it represents the VALUE of the Map (since JPA allows people, for some reason, to use the Map field as shortcut for the VALUE). Consequently KEY(m) has no meaning at all. KEY(e.map) has meaning, but you aren't using that.

**Comment by beikov** [comment]
Take a look at the example in the JPA spec in section 4.4.4
```
SELECT i.name, VALUE(p)
FROM Item i JOIN i.photos p
WHERE KEY(p) LIKE '%egret'
```

Using the alias of the joined map with the *KEY* expression is how it is supposed to be used. Being able to omit *VALUE* is also clearly specified in that section.

**Comment by andyjefferson** [comment]
I refer to what makes sense to a human, not what the "JPA spec" includes. 
[The JPA spec includes the ugly Criteria API, but that doesn't mean it is the right thing to inflict on people]

**Comment by beikov** [comment]
Ah, ok sorry, thought you were thinking this is illegal syntax.
I guess to be able to map that to a concrete sql join alias you have to use the join alias. Otherwise, how would you know which joins' key to use in an example like this...

```
SELECT i.name, VALUE(p1), VALUE(p2)
FROM Item i 
JOIN i.photos p1 ON p1.someValue = 1
JOIN i.photos p2 ON p2.someValue = 2
WHERE KEY(p1) LIKE '%egret' OR KEY(p2) LIKE '%egret'
```

... if you replace *p1* and *p2* with *i.photos*?

**Comment by andyjefferson** [comment]
Test passes on master branch (5.1). Not yet backported to 5.0


For the record, what would have been a better JPQL syntax (IMHO) would have been
```
SELECT o.name FROM Document d 
LEFT JOIN d.contacts contactmap 
LEFT JOIN KEY(contactmap) contactType 
LEFT JOIN VALUE(contactmap) contact
LEFT JOIN contactType.owner o 
```
i.e the basic join on the map field representing the Map itself (as opposed to the key or value, so better reflects the object model). But then that is what you get when having a query language that tries to be SQL and at the same time object based, and ends up being neither of the two.
