### ISSUE TITLE
Support JPA MapKeyClass

### ISSUE THREAD

**Issue by beikov** [datanucleus/datanucleus-core#185]
Currently the code in `org.datanucleus.store.types.containers.MapHandler:156` _defaults to java.lang.Object_ if no key type can be inferred when checking generics. This should honor the class defined via `MapKeyClass` otherwise it infers the wrong type when using raw types and fails to boot.

**Comment by andyjefferson** [comment]
Moved to https://github.com/datanucleus/datanucleus-api-jpa/issues/70
since this is totally JPA metadata specific

**Comment by andyjefferson** [comment]
Now supported in GitHub master and 5.0 branches of datanucleus-api-jpa
