### ISSUE TITLE
Extend bean validation to object loading

### ISSUE THREAD

**Issue by stevespringett** [datanucleus/datanucleus-core#187]
Currently, support for bean validation exists on commit, update, and delete, which itself is good.

A security best practice is to always validate input from untrusted sources, and an external database is, by definition, typically always outside the applications trust boundary and therefore it's data is untrusted.

I would like the ability to perform bean validation on load, when queries are made to retrieve objects. Yes, this can be done after the objects are returned from a query, but I believe it's better to do this type of validation as close to the actual database layer as possible. Besides, there's no reason to keep objects that fail validation in the L1/L2 cache. So having this type of validation in the core makes sense, and of course having a way to provide that capability via JDO and JPA.

**Comment by andyjefferson** [comment]
If wanting such features then you need to consider contributing it via a pull request, with some documentation of how it is enabled etc.

**Comment by andyjefferson** [comment]
No contrib provided, and user can implement this themselves using postLoad and hooking in any validation at that stage. Won't be done unless contributed
