### ISSUE TITLE
WeakValueMap is no longer used; remove it

### ISSUE THREAD

**Issue by andyjefferson** [datanucleus/datanucleus-core#203]
This was effectively replaced during 5.0 lifecycle by ConcurrentReferenceHashMap which correctly deals with concurrency.

**Comment by zchovan** [comment]
Could you add a reference to this in the migration guide? Thanks!

**Comment by andyjefferson** [comment]
The migration guide http://www.datanucleus.org:15080/products/accessplatform_5_2/migration.html does not go into implementation specifics (since users don't need to change anything). This issue is simply remove an internal class that is not used. If you really want something in some document then providing a GitHub PullRequest for the relevant document is the way to go, thanks.
