### ISSUE TITLE
Collections.sort() on persistent List not saved to database with Java 8

### ISSUE THREAD

**Issue by aley2003** [datanucleus/datanucleus-core#221]
Tested with Datanucleus 5.0.8, 5.1, Java 1.8.0_112 on Windows:

A Collections.sort() on a persistent List does not mark the List or List elements dirty (I guess) and so the changed List order will not be saved to the database (see test case).
The behavior is new with Java 8. No problem in Java 7. I think Java 8 has changed the way Collections.sort() works. In Java 8 this is a direct sort of the array in a ArrayList for example.

[test-jdo-list-sort.zip](https://github.com/datanucleus/datanucleus-core/files/1026058/test-jdo-list-sort.zip)

**Comment by andyjefferson** [comment]
These likely work with core master after simply deleting the overrides to the Java 8 mutator methods (sort, replaceIf etc) in the DN wrapper classes. Not checked

**Comment by aley2003** [comment]
I suspect the Problem is not resolved yet. 
I have checked with my test case and do not get a sorted list.
I have tried to track down the Problem by way of example ArrayList. 
In Java 8 sorting in Collections has changed, especially Collections.sort(). 
Collections.sort() calls ths sort() function of the List now.
org.datanucleus.store.types.wrappers.ArrayList.sort() calls super.sort(comp). super is Java.util.ArrayList. 
Java.util.ArrayList.sort() calls Arrays.sort((E[]) elementData, 0, size, c). List.set() will be not be called. 
I guess this ist the reason, sort does not work on Java 8. 
Java 7 Collections.sort:
`    public static <T extends Comparable<? super T>> void sort(List<T> list) {
        Object[] a = list.toArray();
        Arrays.sort(a);
        ListIterator<T> i = list.listIterator();
        for (int j=0; j<a.length; j++) {
            i.next();
            i.set((T)a[j]);
        }
    }
`
Java 8 Collections.sort:
`    public static <T extends Comparable<? super T>> void sort(List<T> list) {
        list.sort(null);
    }
`
list.sort() sorts the elementData Array of the list directly without calling set().

**Comment by andyjefferson** [comment]
Works for me. sort calls the List wrapper .sort() method, which calls AbstractList.sort, which results in multiple calls to the List wrapper .set() method. But then your log would reveal such

**Comment by aley2003** [comment]
With 5.1.0-release or the current 5.1.1-snapshot?

**Comment by andyjefferson** [comment]
Both

**Comment by aley2003** [comment]
I have done some additional Tests.
It works with LinkedList but not with ArrayList. I think there is an optimization in ArrayList in Java 8 which does not call set any longer.

**Comment by andyjefferson** [comment]
Your "test" DECLARES a field as List and INSTANTIATES it as ArrayList. This consequently uses org.datanucleus.store.types.wrapper.backed.List. It passes like that. Instantiating as LinkedList also passes, and Vector.

Consequently I have to assume you mean DECLARING the field as ArrayList, yes that doesn't work. But then all best practice guides for Java collections would say use the interface declaration (and you would never even be able to persist a field declared as ArrayList in Hibernate!!). If that case is really a problem for you then it is a separate issue, and you can then provide a pull request for whatever the fix is in the usual place; no interest from me in that one.

**Comment by aley2003** [comment]
The declarations of my test lists look like:
List<Child> linkedList = new LinkedList<>(); // Works
List<Child> arrayList = new ArrayList<>(); // Does not work

My sort Looks like:
Collections.sort(arrayList, new Comparator<> ...);

I run my tests with core 5.1.1-SNAPSHOT on Java 1.8.0_112.

The log Shows the following classes for the lists:
DEBUG [DataNucleus.General] - Children Class: 
 Linked: class org.datanucleus.store.types.wrappers.backed.LinkedList 
 Array: class org.datanucleus.store.types.wrappers.backed.ArrayList

I do not understand the difference between your and my tests.
How can I upload my test case?

**Comment by aley2003** [comment]
I tried to upgrade my Project from 5.0.9 to 5.1.4 and noticed, that the sort Problem still exists.

As said before I think it only exists for Lists implemented as ArrayList.

org.datanucleus.store.types.wrappers.ArrayList.sort() calls super.sort(), which is java.util.ArrayList.sort().
The implementation of java.util.ArrayList.sort() in Java  8 delegates the sort to Java.util.Arrays.sort() with
`Arrays.sort((E[]) elementData, 0, size, c);`
So there is a direct sort of super java.util.ArrayList.elementData. 
No org.datanucleus.store.types.wrappers.ArrayList.delegate will be used, no `public E set(int index, E element)` will be called. BTW: Why is it super.sort() instead of delegate.sort()?
I do not see any way Datanucleus could notice the new sort order of the Elements. Do I overlook something?

**Comment by andyjefferson** [comment]
As already said, when you have a problem you need to get the code and work out and contribute the solution. No resource here.

v5.1 has "datanucleus.type.wrapper.basis" in its docs, but that is likely only part of your problem

**Comment by aley2003** [comment]
As far as I understand the docs for the property "datanucleus.type.wrapper.basis" this could be a Workaround, but I do not know from the docs, what SCO wrapper implementation will be used. So for me the simpler Workaround is to use LinkedList instead of ArrayList for the implementation.

Is there any documentation about the SCO wrapper architecture and implementation in Datanucleus? How to use the delegate? Why is there super.sort() instead of delegate.sort() in ArrayList? 
It is not easy to understand a complex Framework like Datanucleus from source code only.
