### ISSUE TITLE
Don't attempt to enhance metadata annotations

### ISSUE THREAD

**Issue by clr-apache** [datanucleus/datanucleus-core#249]
Apply the patch in https://issues.apache.org/jira/browse/JDO-764 and many jdo tck test cases fail.

The annotations are successfully used to enhance classes, but during runtime the annotations are enhanced, leading to failures.

**Comment by andyjefferson** [comment]
Please provide a stand-alone testcase following http://datanucleus.org/documentation/problem_reporting.html#jdo  
This simply means, put the model classes into the "src/main/java/mydomain/model" directory, and put the test into "src/test/org/datanucleus/tests" directory, and update the persistence.xml

That way there is no need to have to use some huge test suite, apply patches, install schema to a very slow database, and the rest, just to see one problem.

**Comment by andyjefferson** [comment]
Nothing will be "enhanced" at runtime unless you have runtime enhancement enabled (i.e java-agent), and the JDO TCK doesnt do that anyway. Can't see a problem.
