### ISSUE TITLE
Enable lgtm.com PR integration

### ISSUE THREAD

**Issue by rneatherway** [datanucleus/datanucleus-core#253]
## Feature Request:

Have you considered turning on the PR integration now that you've fixed most of the alerts? lgtm.com can comment on PRs, or just have a click-through from the 'Checks' section at the bottom of the PR. Here's an example of it in practice: https://github.com/statsmodels/statsmodels/pull/3811

**Comment by andyjefferson** [comment]
Not something I'd consider any time soon, thanks. Will reassess in the future if people get involved in the project.
Also not something that applies to the "datanucleus-core" GitHub project, hence why i'm closing this.

**Comment by rneatherway** [comment]
Fair enough :-)
