### ISSUE TITLE
API changes report for DataNucleus Core

### ISSUE THREAD

**Issue by lvc** [datanucleus/datanucleus-core#266]
The review of API changes for the DataNucleus Core library since 5.0.1 version: https://abi-laboratory.pro/java/tracker/timeline/datanucleus-core/

The report is generated for jars found at http://central.maven.org/maven2/org/datanucleus/datanucleus-core/ according to https://wiki.eclipse.org/Evolving_Java-based_APIs_2.

Thank you.

![datanucleus-core-2](https://user-images.githubusercontent.com/1517837/31112203-056ec36c-a81b-11e7-9b4f-98dbb8192187.png)
![datanucleus-core-1](https://user-images.githubusercontent.com/1517837/31112202-056e991e-a81b-11e7-8167-f653e8dce3bf.png)

**Comment by andyjefferson** [comment]
This is not an "issue". Thanks
