### ISSUE TITLE
Metadata#determineSuperClassName fails under certain circumstances

### ISSUE THREAD

**Issue by andi-huber** [datanucleus/datanucleus-core#269]
I'm working on JEE support for Apache Isis, which uses JDO as persistence layer. First step is to get everything working on payara 4.1.2 (using DataNucleus 5.1.4). We are almost there, however one issue remains:

Having a persistence-capable class d.d.A that extends on abstract class d.d.B, where d.d.A is deployed with a skinny-war-file and d.d.B is packaged in a lib that is shared on the JEE container.

(skinny-war meaning: we prepare the JEE container with shared libraries and shared domain objects and deploy only a subset of domain classes with the web-app war package)

Now when deploying d.d.A, then letting JDO load d.d.A, and then later changing d.d.A's source code, then compiling and redeploying the new d.d.A, we run into DataNucleus Metadata issues:

```
org.datanucleus.metadata.InvalidClassMetaDataException: Class "d.d.A" has a persistence-capable-superclass d.d.B which is NOT a superclass of the class.
at org.datanucleus.metadata.AbstractClassMetaData.determineSuperClassName(AbstractClassMetaData.java:638)
```

```
void determineSuperClassName(ClassLoaderResolver clr, Class cls) {
    ...
    Class pcsc = clr.classForName(persistableSuperclass);
    ...
    if (... !(pcsc.isAssignableFrom(cls)))  {
         throw new InvalidClassMetaDataException(...);
    }
    ...
}
```

It seems, that during Metadata processing d.d.B gets picked up by two different class-loaders, where a subsequent d.d.B==d.d.B check results to false, while true is expected.

**Comment by andi-huber** [comment]
Proposed fix via PR 270
https://github.com/datanucleus/datanucleus-core/pull/270

**Comment by andyjefferson** [comment]
Unfortunately, applying that patch results in test failures from https://github.com/datanucleus/tests/blob/master/jdo/identity/src/test/org/datanucleus/tests/PersistentAbstractClassesTest.java whereas without it it passes (and always has). This is a case where implementation classes are generated.

**Comment by andyjefferson** [comment]
e.g try this

```
if (persistableSuperclass.equals(fullName) || (!clr.isAssignableFrom(pcsc, cls.getName()) && !pcsc.isAssignableFrom(cls)))
{
    ...
}
```

**Comment by andi-huber** [comment]
Hi Andy,
in our particular case pcsc.isAssignableFrom(cls) evaluates to false where it should evaluate to true, so lets have a look at the truth table where 
a:=clr.isAssignableFrom(pcsc, cls.getName()
b:=pcsc.isAssignableFrom(cls)

a , b , !a && !b , expected
------------------------
0 , 0 , 1 , 1 ... ok
1 , 1 , 0,  0 ... ok
1,  0 , 0 , 1 ... will not work
0 , 1 ... should/will never happen

Right now, I'm fetching the test suite. Let me have a closer look ...

**Comment by andi-huber** [comment]
test-suite passes if we do the following ...
```
if (persistableSuperclass.equals(fullName) || !clr.isAssignableFrom(pcsc.getName(), cls) )
{
    ...
}
```
This forces our is-assignable-from-check to use the class-loader of cls to do the check and not the class-loader of the super class. (The class-loader of the super-class might not be aware of all super-class'es implementing classes, but the other way around should be guaranteed.)

I'm testing whether this resolves my issue ...

**Comment by andi-huber** [comment]
If my testing procedure was right, PR 271 finally solves our issue:
https://github.com/datanucleus/datanucleus-core/pull/271

**Comment by andyjefferson** [comment]
Pull request merged, so marking as fixed.

**Comment by andi-huber** [comment]
thanks!!!
