### ISSUE TITLE
EnhancementHelper keeps references to classes after deploy/undeploy cycle

### ISSUE THREAD

**Issue by andi-huber** [datanucleus/datanucleus-core#272]
I'm afraid, with #269 we were only fighting symptoms, but I believe we now got to the root cause of this issue ...

We are using DataNucleus (DN 5.1.5-SNAPSHOT) on JEE (Payara 4.1). DN's jar files are prepared on the JEE container as shared libraries. So when the container starts it loads DN's classes just once. This is a 'non-managed' scenario for DN.

When deploying a web-app that uses DN, we bootstrap a PersistenceManagerFactory, while providing DN the ClassLoader of the current web-app, (lets call it ALICE).

```
PersistenceManagerFactory  persistenceManagerFactory = JDOHelper
    .getPersistenceManagerFactory(datanucleusProps, ALICE);
```

During this process EnhancementHelper registers all persistable classes and keeps references in a static field of type Map.

Now after an undeploy/change-code/deploy cycle of the web-app, the web-app bootstraps a new PersistenceManagerFactory providing DN with a different ClassLoader instance than before, (lets call it BOB). (In this scenario EnhancementHelper still holds all references to the classes loaded before by ALICE.)

Now class-loading/class-casting issues might occur! The reason we found is the following:

DN populates ClassMetaData information (on every deployment) using the plugable ClassLoaderResolver. But somehow class-loader ALICE leaks from the EnhancementHelper's registered classes into this population mechanism via code similar to this:

```
protected void initialiseClassMetaData(ClassMetaData cmd, Class cls, ClassLoaderResolver clr){
	...
	populateAbstractClassMetaData(cmd, clr, cls.getClassLoader() /* could be ALICE */ ); 
	...
}
```
... where cls's ClassLoader somehow originates from a lookup at EnhancementHelper's registered classes. This way the default implementation of ClassLoaderResolver uses ALICE as the primary ClassLoader and MetaData gets corrupted.

---

As a workaround we, found that with the end of a web-app's life-cycle (meaning when un-deploying),  clearing EnhancementHelper's registered classes of any that were loaded before by ALICE (but leave others) solves the issue.

We have to resort to reflection in order to access the private static 'registeredClasses' field of EnhancementHelper.

Here's the life-cycle (yet experimental) helper class that currently does the DN shutdown:
https://github.com/apache/isis/blob/dev/2.0.0/ISIS-1767-jee-7/core/runtime/src/main/java/org/apache/isis/objectstore/jdo/datanucleus/DataNucleusLifeCycleHelper.java

We can live with that, but maybe there is a more robust/profound solution to this issue.

Thanks for any help or advice.

br,
Andi Huber

**Comment by andyjefferson** [comment]
Indeed, it keeps a map just for convenience of generating instances for use in persistence, and doesn't allow for other use-cases. Do you need a method on that class to unregister some classes?

FYI, EnhancementHelper is/was simply a copy of the JDO standard JDOImplHelper which did what you see there plus much more, much of which was stripped out in v5.1. Issues #261 and #264 both impact on EnhancementHelper and will make other parts of that class redundant .. but not doing those until v5.2 since they change the enhancement contract.

**Comment by andi-huber** [comment]
Andy, thanks for the insight! 

I guess ultimately it would be nice to have a DN method somewhere, that when called purges DN's state and any meta-data associated with it in the context of the class-loader, that was used for bootstrapping this state.  Maybe EnhancementHelper is the only place that keeps state at this point!? 

Meaning it would be nice not to need a Helper-Class for this as mentioned above.

So if this gets solved with v5.2 I believe we can live with our current workaround till then.

**Comment by andyjefferson** [comment]
When a PMF is closed then its MetaDataManager is closed, and hence all metadata is purged. That part should not be a problem.

I've reinstated the original `EnhancementHelper.unregisterClasses(ClassLoader)` which presumably would allow you to unload all classes for a loader. No idea if that is equivalent to your workaround method

**Comment by andi-huber** [comment]
Cool, I believe, that is exactly what we needed! 

And you might be right, that we don't need to explicitly un-manage classes from meta-data, since meta-data get's thrown away anyway.

So without having tested it yet I close this issue.

Thanks again!
