### ISSUE TITLE
MetaDataParser assumes SAXParser instance can be shared between threads

### ISSUE THREAD

**Issue by siepkes** [datanucleus/datanucleus-core#279]
The `SAXParser` instance in the `MetaDataParser` class seems to be shared between threads and used concurrently (at least that's what we observed when used in an OSGi environment). When accessed concurrently the parser will throw a `SAXException` with the message "FWK005 parse may not be called while parsing.". Since it is an concurrency issue the issue is hard to reliably reproduce.

The [documentation](https://docs.oracle.com/cd/E17802_01/webservices/webservices/docs/1.5/api/javax/xml/parsers/SAXParserFactory.html) of the `SAXParserFactory` says:

> An implementation of the SAXParserFactory class is NOT guaranteed to be thread safe. It is up to the user application to make sure about the use of the SAXParserFactory from more than one thread. Alternatively the application can have one instance of the SAXParserFactory per thread. An application can use the same instance of the factory to obtain one or more instances of the SAXParser provided the instance of the factory isn't being used in more than one thread at a time.

While strictly speaking the above text is only about the `SAXParserFactory` and the documentation of the `SAXParser` instances it creates says nothing about thread safety this must apparently be interpreted as `SAXParser` instances also being not thread safe (since it starts throwing exceptions when accessing those instances concurrently).

**Comment by andyjefferson** [comment]
Thx for the report. If you use metadata parsing in a way that this causes a problem then kindly get the code and contribute a fix.

**Comment by siepkes** [comment]
I don't think i'll be able to create a tests which reliably reproduces the behavior since it is a concurrency  thing. It only occurs in our (larger) OSGi application based on Felix. I can however contribute a fix which improves the "correctness" of the code which is verifiable (ie. ensure the `SAXParser` isnt shared between threads). Would that work?

**Comment by andyjefferson** [comment]
Contributing a fix that doesn't impact on all existing tests is all that is needed

**Comment by siepkes** [comment]
I'm encountering an design / compatibility issue; The local variable `parser` is scoped `protected`. Combined with the `MetaDataParser` class being sub-classable (ie not `final`) and being scoped `public` that makes the `parser` variable (semi) public API; There could be subclasses depending on direct access to that variable. A quick search through the DN code base seems to indicate nothing within DataNucleus does that. 

I propose to make the `parser` variable `private` scoped and ensure proper locking is used. A possible alternative would be to use `ThreadLocal`. However `ThreadLocal` use is often prone to resource / memory leaks so I would rather not use that. An other alternative would be to stop all callers from sharing a `MetaDataParser` instance. However since most of this concurrent access comes from static method calls that might also be kinda hard to solve without having to refactor a large portion of code.

Would making the variable private work and leave the locking inside the `MetaDataParser` class work  for you?

**Comment by andyjefferson** [comment]
No problem with that idea
