### ISSUE TITLE
Exception thrown if base class has no attributes

### ISSUE THREAD

**Issue by chrisco484** [datanucleus/datanucleus-core#287]
Test case attached with a simple 2 class model reproducing the issue:

[exceptionOnBaseClassWIthNoAttributes.zip](https://github.com/datanucleus/datanucleus-core/files/1867696/exceptionOnBaseClassWIthNoAttributes.zip)

**Comment by andyjefferson** [comment]
Thx for the report. As already said on groups.io, you need to provide an update to _datanucleus-rdbms_ since this is totally to do with **datanucleus.rdbms.dynamicSchemaUpdates**, consequently the issue should be raised on that plugin. Thx
