### ISSUE TITLE
JPAEntityManager.unwrap context leak

### ISSUE THREAD

**Issue by veselov** [datanucleus/datanucleus-core#290]
Hello.

I'm switching to DataNucleus, so the problems I'm seeing are mostly integration related I guess.
I am trying to get the underlying database connection from Nucleus, using JPA.
Calling `JPAEntityManager.unwrap(java.sql.Connection.class)` I see some funny behavior.
First, there is a check to see if used `NucleusConnection` is an instance of `java.sql.Connection`. AFAICS, it never can be, so this condition will always be false.
Second, connection object is already retrieved, but the reference is lost, and `close()` is never called. So the underlying connection remains unusable, leading to "The Connection was acquired by the developer and must be closed before using the persistence API." error, making the context impossible to dispose of.

I don't know if the `instanceof` makes sense, but if the connection is not returned, it should be closed within `unwrap()` method.

**Comment by andyjefferson** [comment]
No idea what "the reference is lost" refers to. The fact is that it is NOT for the user to close anything, and the connection is what the JPA provider is using, so if the user closes it then the JPA provider has the rug pulled out from under it. If a connection is ALLOCATED explicitly for this unwrap (when non-transactional for example) then it IS closed by the JPA provider).

**Comment by veselov** [comment]
I'll re-open the issue in datanucleus-api-jpa.
I'm sorry, I am probably using the wrong terminology.
Calling `em.unwrap()` with `java.sql.Connection` effectively causes the underlying datanucleus connection object to lock itself, as the returned "Connection" object is a wrapper. If the wrapper is not closed, the underlying connection remains locked. If the connections is locked, the transaction can't even be operated upon (hence the error message quoted in the description). The wrapper is created, but never returned to the caller of `em.unwrap()`, causing the "leak" (for the lack of the better term).
