### ISSUE TITLE
No support available for embedded jars of the form jar:file:<app_jar_path>!<path_inside_app_jar>!/plugin.xml

### ISSUE THREAD

**Issue by piotrchowaniec** [datanucleus/datanucleus-core#292]
The problem reported by https://stackoverflow.com/questions/50151397 is caused by wrong way of finding plugin.xml file when DataNucleus-* files are embedded in the application jar (application is assemble as single executable jar). In particular the implementation in org.datanucleus.plugin.NonManagedPluginRegistry cannot properly resolve path to plugin.xml file when path is like: jar:file:<app_jar_path>!<path_inside_app_jar>!/plugin.xml. Instead of looking for embedded jar the application jar is used to find plugin.xml file. 

To reproduce the problem one can use the example project posted [here](https://github.com/piotrchowaniec/spark-hive-jar)

In my case the problem was with 3.2.10 version, but as I can see there is no fix for this in any later version.

**Comment by piotrchowaniec** [comment]
I've added a fix for this on my fork: https://github.com/piotrchowaniec/datanucleus-core/tree/3.2.13
I cannot fix this directly on 3.2 branch because after 3.2.13 the method signature org.datanucleus.util.MultiMap#remove was changed and Spark is using the older version.

**Comment by andyjefferson** [comment]
Everything but 5.1 is not maintained. I'll apply your "fix" to master branch, thx.
