### ISSUE TITLE
Too long select item alias is shortened only for select item even when used in order by

### ISSUE THREAD

**Issue by beikov** [datanucleus/datanucleus-core#300]
## Bug Report, attach a testcase using [problem guide](http://www.datanucleus.org/documentation/problem_reporting.html) and state what version the problem occurs in. Any "Bug" without a testcase will be CLOSED.
Consider a sample JPQL query like 

```
SELECT e.id AS DOCUMENTWITHDEEPSUBQUERYEMBEDDINGVIEW_OWNER_PARTNERDOCUMENT_NAME
FROM SomeEntity e
ORDER BY DOCUMENTWITHDEEPSUBQUERYEMBEDDINGVIEW_OWNER_PARTNERDOCUMENT_NAME ASC
```

This query is translated for PostgreSQL to
```
SELECT "e.id" AS "DOCUMENTWITHDEEPSUBQUERYEMBEDDINGVIEW_OWNER_PARTNERDOCUMENTK51X"
FROM SomeEntity e
ORDER BY "DOCUMENTWITHDEEPSUBQUERYEMBEDDINGVIEW_OWNER_PARTNERDOCUMENT_NAME" ASC
```

It seems the alias is shortened, but apparently this shortening isn't applied for the alias in the order by clause.

**Comment by andyjefferson** [comment]
Nothing to do with datanucleus-core. Suggest that you raise a real bug with test on datanucleus-rdbms since that is the only thing anywhere that touches SQL
