### ISSUE TITLE
Entities do not use the defaults as required by the JPA spec

### ISSUE THREAD

**Issue by beikov** [datanucleus/datanucleus-core#301]
I just noticed that optionality/nullability doesn't use the proper default as required by the JPA spec 11.1.6 as can be reproduced with the attached test case. I assume that other defaults aren't adhered to as well, but didn't run into any problems with my tests so far.
[datanucleus-test.zip](https://github.com/datanucleus/datanucleus-core/files/2217305/datanucleus-test.zip)

**Comment by andyjefferson** [comment]
Firstly, 11.1.6 states very clearly that "optional" is a **hint** only. Secondly, you are only referring to the JPA MetaModel, which is not what defines behaviour; it is an API only. Thirdly, that API is implemented in datanucleus-api-jpa, as with all JPA specifics. Thx

**Comment by andyjefferson** [comment]
See https://github.com/datanucleus/datanucleus-api-jpa/issues/107
