### ISSUE TITLE
Any hope for DN to support Spring Data?

### ISSUE THREAD

**Issue by andi-huber** [datanucleus/datanucleus-core#320]
Hi @andyjefferson 

This might be the wrong place to ask, but as an `Apache Isis` contributor, I'm curious whether there are any plans for DataNucleus to make a `spring-data-jdo` [1] module?

Long story short: `Apache Isis` was initially built around JDO some years ago. We do now re-platform the entire framework on top of `String Data`. Consequently we have to drop JDO support, at least for now. (I was a bit shocked to learn, that Spring dropped JDO support [2] with version 5. Apparently they regarded it a 'niche product'.)

Now I suspect that the entire `Apache Isis` user community does use JDO, so there's at least some people that have invested time into projects utilizing DataNucleus and might be willing to continue so, as long as we can support it.

This question is related to the user mailing list entry here [3].

Cheers, Andi

[1] https://jira.spring.io/browse/DATACMNS-96
[2] https://github.com/spring-projects/spring-framework/issues/18702
[3] https://lists.apache.org/thread.html/3b8adc4cda22a93de90cdcd21ed6d0041821edb36d978da603cbe28d@%3Cusers.isis.apache.org%3E

**Comment by andyjefferson** [comment]
Why would "I" have to do it ? What would it "do" ? I personally have zero interest in Spring Data, and they (Spring) have never "done" anything for this project (neither JDO nor JPA). No plans from me, as a result. Obviously others can plan for what they want to do and I'll include things if they want them here

**Comment by andi-huber** [comment]
Ok understood, this was just a question, no request implied.
Thx
