### ISSUE TITLE
Multitenancy query cache problem

### ISSUE THREAD

**Issue by jfirles** [datanucleus/datanucleus-core#321]
I'm trying to use the multitenancy option in datanucleus, but it not works at expected.

When I set the "datanucleus.tenantId" property at the PersistentManager for one tenant, I can get the objects of that tenant; but, in the same PersistenceManager I change the tenantId to another, I get the same objects of the first tenant.

I have checked that the problem is related with the query cache (QueryDatastoreCompilationCache) in the core project. The first tenantId setted persist over the later queries.
The key used for cache the queries not complain the multitenancy.

The test project is in that repository
https://github.com/jfirles/test-jdo

I attach a patch that resolves the problem:
[datanucleus-core-multitenancycache.patch.txt](https://github.com/datanucleus/datanucleus-core/files/3407137/datanucleus-core-multitenancycache.patch.txt)
I don't know if that patch impacts in other features

**Comment by racoonman** [comment]
Same problem here.

The patch corrects the problem, but I'll be more confident if somebody from the development team confirms and fix this issue for next releases
