### ISSUE TITLE
Use SLF4J Instead of Log4J Directly

### ISSUE THREAD

**Issue by belugabehr** [datanucleus/datanucleus-core#327]
Use SLF4J for logging facade.

http://www.slf4j.org/faq.html

**Comment by andyjefferson** [comment]
No thanks. That would hardcode a requirement of everyone having to have SLF4J present, as opposed to ... people use what logging system they want (log4j, or java.util.logging) with no compile/runtime requirement.

**Comment by belugabehr** [comment]
@andyjefferson Are you familiar with SLF4J?

It is as you describe, it is a library much like NucleusLogger.  It is only a facade and allows the end user to slide in their own logging framework (log4J, logback, apache logging, jul, etc.)

**Comment by andyjefferson** [comment]
I started with Java when it originated. I've met SLF4J. And no, as already said, it provides NO advantage (of using instead of NucleusLogger) and a significant disadvantage. Just NO
