### ISSUE TITLE
StoreDataManager FCO Data Handling

### ISSUE THREAD

**Issue by belugabehr** [datanucleus/datanucleus-core#333]
https://github.com/datanucleus/datanucleus-core/blob/fb2737393a997aa509467a6e52022c7f164493c8/src/main/java/org/datanucleus/store/StoreDataManager.java#L67-L84

I'm not sure if this is a bug or what the intent is here, but it looks to me that both FCO data and non-FCO data do the same thing even though the comments seem to indicate otherwise.

**Comment by andyjefferson** [comment]
Nope. No bug there. "getName" was changed years ago to pass different things for different types of store data. Could merge into 1 block, but then there are way more important things to do

**Comment by chrisco484** [comment]
It looks like getName() became a polymorphic method at some stage and the above code isn't yet leveraging that fact.

The only thing I would say is that merging into a single block as Andy suggested avoids a call to data.isFCO but that's probably not an expensive call.
