### ISSUE TITLE
OffsetTimeLongConverter is broken because OffsetTime.from(LocalTime) always throws

### ISSUE THREAD

**Issue by kluever** [datanucleus/datanucleus-core#342]
https://github.com/datanucleus/datanucleus-core/blob/dcae0328a22a06113d82dde683a172926e567531/src/main/java/org/datanucleus/store/types/converters/OffsetTimeLongConverter.java#L39-L40

`OffsetTime.from(LocalTime)` always throws because there is no zone information available in a `LocalTime` instance. Therefore, I suspect the `OffsetTimeLongConverter` in datanucleus-core is broken (will always throw a `DateTimeException`):

```java
Caused by: java.time.DateTimeException: Unable to obtain ZoneOffset from TemporalAccessor: 11:47:44 of type java.time.LocalTime
        at java.time.ZoneOffset.from(ZoneOffset.java:348)
        at java.time.OffsetTime.from(OffsetTime.java:292)
```

Note: this was discovered thanks to a static analysis plug-in written using http://errorprone.info/

**Comment by andyjefferson** [comment]
If you think something is a problem then demonstrate it as per the issue template, and/or a pull request

**Comment by kluever** [comment]
This issue isn't actually impacting me -- I don't use your library -- I just discovered this bug while running my static analysis checker over a large codebase (which happens to include your library).

Here's a MCVE. Do with it what you'd like:

```java
  @Test
  public void testDataNucleus_issue342() {
    OffsetTimeLongConverter converter = new OffsetTimeLongConverter();
    assertThrows(DateTimeException.class, () -> converter.toMemberType(42L));
  }
```
