### ISSUE TITLE
JPQL Integer literals come out as Long values

### ISSUE THREAD

**Issue by beikov** [datanucleus/datanucleus-core#356]
A query like the following:

```
select 1
from Entity a
```

seems to produce `Long` values although I clearly intend a `Integer`. The JPA specification mandates that JPQL numeric literals use Java Language semantics, so this should produce `Integer` values. If I had written `1L`, a `Long` should be returned.

See section 4.6.1 in the JPA 2.2 specification for more details.

**Comment by andyjefferson** [comment]
Can't reproduce with any current code.
