### ISSUE TITLE
How to auto create jdo entities based on db tables?

### ISSUE THREAD

**Issue by AlphaWang** [datanucleus/datanucleus-core#362]
Hi team, 

There's a `datanucleus.schema.autoCreateAll` which support auto creating db tables based on jdo entity class, but I'm wondering what is the best practice to handle existing db tables? Is there a way to auto create jdo entities based on db tables?

**Comment by andyjefferson** [comment]
Support forums are for asking questions. This is an issue tracker

**Comment by AlphaWang** [comment]
> Support forums are for asking questions. This is an issue tracker

Sorry, could you please let me know the support forum link?

**Comment by chrisco484** [comment]
> > Support forums are for asking questions. This is an issue tracker
> 
> Sorry, could you please let me know the support forum link?

Hi @AlphaWang ,

This link contains the links to two support forums in point 4:

https://www.datanucleus.org/support.html

The 'Groups' is probably your best bet - seems like the gitter option is newer but both are active.
