### ISSUE TITLE
Multi tenancy override tenant or, and EntityProvided tenant

### ISSUE THREAD

**Issue by spassignat** [datanucleus/datanucleus-core#369]
The TenantProvider is a great feature but sometime the tenant is only available after the initialization of the ExecutionContext. 

For example, when you have a user belonging to a "root" tenant, creating data (ex: an order) for another tenant, this data containing information of the "owner tenant". (Order -> Seller -> code, with code being the tenantId).
In such situation, the tenant need to change for that particular object and also for all others in the transaction.

The actual solution is to change the tenant in a TenantProvider from the "business" code, and sometime after the ExecutionContext has been created. This solution is more a workaround, as the initial tenant in TenantProvider had may be already used earlier.

Another solution could be a TenantProvider at the persistent object level. 
```
@Persistent
@TenantProvider (OrderTenantProvider.class)
class Order{
private Seller seller;
```

The TenantProvider:
```
class OrderTenantProvider implements ObjectTenantProvider{
  public String provideTenant(Object obj){
    return ((Order)obj).getSeller().getCode();
  }
```

DN could also check if this Tenant is part of the tenant-read-ids (nice to have)

**Comment by andyjefferson** [comment]
Overriding the tenantReadIds on a per-PM/EM basis is problematic because the XXXRequest in datanucleus-rdbms are cached on a StoreManager-basis (and the statement is dependent on the number of tenantReadIds), and you would then have to throw away any such caching.

**Comment by andyjefferson** [comment]
The other factor that should be covered in this is the situation where a user has put @Multitenant on a class but hasn't specified the tenantId as a minimum. Currently if the schema is not yet created it will omit the MULTITENANCY column. Probably a better way to do it would be to always create the MULTITENANCY column, but make it nullable, and either have a default generated tenantId when not provided, or put null into it.

**Comment by spassignat** [comment]
In my memory a column tenant_id is always generated (I had to remove some of them). I can't test actually due to a maven dependency download and mirrors, ...
Default tenant is a great idea. I though it was actually the case. Another idea would be to skip tenant, if not provided or if a predefined value is provided ex: DataNucleus_Root (kind of root access).

My actual usage of multitenancy is to allow some users (or group of users) : 
- to create, read and update data belonging to a list of tenants. 
- to create data in any tenants, the tenant can be found or computed in the created object graph (the purpose of this github issue).
- to read and to update data without regards to tenant (kind of root users)

I tried to tweak the provider to make this happen but due to statement "cache" (1), I finally had to create one EntityManagerFactory per tenant configuration (which has some impacts on memory, caches, connection pooling, ...) and distinguished (2) insert,update,delete transaction from others. (because tenant has a kind of priority over tenant-read-ids)

(1) in fact in a Find or Insert object, there is a map of SQL Statement which contains the first tenant (A) used. Then when you find or create an object in another tenant (B), it goes in the tenant (A).   

 (2) for broad read operation, tenant-id need to be null to allow use the tenant-read-ids.

**Comment by andyjefferson** [comment]
No, always creating a multitenancy column (when _tenantId_ specified) was **not** always the case. It was for RDBMS and not for others (e.g Cassandra). This is changed in #407 so that each class (that wants to be treated as multitenant) has to specify the `@Multitenant` annotation (or XML equiv) (disabled attribute now dropped from the annotation) and then it will always create the column. i.e class-specific and explicit, for consistency with specification of everything else in DN.

The handling of tenantId and tenantReadIds is unchanged. A PMF/EMF has to know which tenant to create for, hence there is always a 1-1 correspondence between PMF/EMF and the tenant to write for (but not read for).

**Comment by andyjefferson** [comment]
No clearer definition of the problem relative to current codebase provided so closing for now
