### ISSUE TITLE
Add PC Class and id to EntityNotFoundException message

### ISSUE THREAD

**Issue by spassignat** [datanucleus/datanucleus-core#381]
Hi,
The actual exception message (javax.persistence.EntityNotFoundException: No such database row) is not very helpful when the missing object is not the one queried but one in the fetch-graph.

Ex: when querying a Person with a fetch graph containing its address, if for any reason the address is not found, we (at least I) think the missing object is the person. It would be very helpful to know the type (or related information) and the id of the missing object.

something like: 
javax.persistence.EntityNotFoundException: No such database row with id <1324,xxx> in table <address> from Entity <Address>

thanks

**Comment by andyjefferson** [comment]
Assume that this will be raised on the plugin where it needs adding, i.e datanucleus-rdbms, so closing this
