### ISSUE TITLE
Non equivalent mutitenancy metadata loading

### ISSUE THREAD

**Issue by spassignat** [datanucleus/datanucleus-core#412]
When loading class multitenancy metadata in **PersistenceNucleusContextImpl**, the condition to determine if a class is multitenanted is not "clear".

```
public boolean isClassMultiTenant(AbstractClassMetaData cmd) {
    if (this.multiTenancyProvider == null && this.config.getStringProperty("datanucleus.TenantId") == null) {
        return false;
    } else {
        return !"true".equalsIgnoreCase(cmd.getValueForExtension("multitenancy-disable"));
    }
}
```

The multiTenancy metadata is loaded differently if the provider is not null with a tenantId null, or if the tenantId is null in the config, which also skip the tenant-read-ids.

It might be better to skip tenantId or tenant-read-ids values during metadata loading.

Why not adding a property in the config to activate multitenancy feature, but still regardless of the tenantId value. It can also set all class as multitenant (which is overridable by the class-metadata), or form rdbms, set the tenant column, ...

**Comment by andyjefferson** [comment]
That method is not used by RDBMS, only by other datastores (Cassandra, MongoDB, HBase, Neo4j) in current code

**Comment by spassignat** [comment]
> That method is not used by RDBMS, only by other datastores (Cassandra, MongoDB, HBase, Neo4j) in current code

That's strange, I'm running on RDBMS and I faced a case, where using properties with a null tenant-id, the multitenancy metadata is not loaded. Debugging went through this code. So I now using a MultiTenancyProvider in all cases.

Here is a call stack with RDBMS:
![image](https://user-images.githubusercontent.com/6451374/131329076-259e3040-18c7-4720-9983-9e8b377889f7.png)

**Comment by andyjefferson** [comment]
And you're not using github master
