### ISSUE TITLE
ExecutionContextImpl.performDetachAllOnTxnEndPreparation has a NPE bug, the bug may be caused by level1Cache

### ISSUE THREAD

**Issue by FlowingFun** [datanucleus/datanucleus-core#421]
I find a NPE bug in ExecutionContextImpl.performDetachAllOnTxnEndPreparation, line number is 4412. The NPE bug may be caused by Level1Cache, the level1Cache default type is soft, so the value object in level1Cache will be removed when the VM is low on memory. When the code "ObjectProvider op = opsIter.next()" on line 4411 is executed, the "op" may be null, then the code "Object pc = op.getObject()" on line 4412  will throw NPE. It is best to add null check before execute the code on line 4412. 
![image](https://user-images.githubusercontent.com/30023473/143537442-fccb692e-4285-4277-a288-46304ec0cba1.png)

**Comment by andyjefferson** [comment]
No reply
