### ISSUE TITLE
Table with name "user" or "users" fails to auto create

### ISSUE THREAD

**Issue by sdyura** [datanucleus/datanucleus-core#422]
i was following the instructions on:
https://www.datanucleus.org/products/accessplatform_5_0/jpa/tutorial.html

i got the same from https://github.com/datanucleus/samples-jpa

and i wanted to use the table name "users" so i changed 1 file that says what the table name is from 

-        <table name="JPA_BOOKS"/>
+        <table name="USERS"/>

and then when i run the code, it does not work, i get a very strange error:

     [java] Error persisting data : Transaction failed to commit
     [java] javax.persistence.RollbackException: Transaction failed to commit
     [java] 	at org.datanucleus.api.jpa.JPAEntityTransaction.commit(JPAEntityTransaction.java:113)
     [java] 	at org.datanucleus.samples.jpa.tutorial.Main.main(Main.java:65)
     [java] Caused by: javax.persistence.PersistenceException: Error(s) were found while auto-creating/validating the datastore for classes. The errors are printed in the log, and are attached to this exception.
     [java] 	at org.datanucleus.api.jpa.NucleusJPAHelper.getJPAExceptionForNucleusException(NucleusJPAHelper.java:316)
     [java] 	at org.datanucleus.api.jpa.JPAEntityTransaction.commit(JPAEntityTransaction.java:107)
     [java] 	... 1 more
     [java] Caused by: org.h2.jdbc.JdbcSQLException: Table "USERS" not found; SQL statement:
     [java] ALTER TABLE USERS ADD COLUMN PUBLISHER VARCHAR(40) NULL [42102-168]
     [java] 	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
     [java] 	at org.h2.message.DbException.get(DbException.java:169)
     [java] 	at org.h2.message.DbException.get(DbException.java:146)
     [java] 	at org.h2.command.Parser.readTableOrView(Parser.java:4770)

if i change the name to MY_USERS, everything works fine again
if i change the name to USER, i get a error again

so i think there is 2 bugs, 1st that it does not work with the name users, and also that the error i get makes totally no sense and i took me a day to work out what it actually meant.

i tested this on H2 and mySQL and it happens on both, so its not related to the Database type

datanucleus was latest stable version: 5.2.8

this used to work fine in datanucleus v3, so this problem started when moving v3 -> v5

[samples-jpa.zip](https://github.com/datanucleus/datanucleus-core/files/7620598/samples-jpa.zip)

**Comment by andyjefferson** [comment]
This is nothing to do with the datanucleus-core plugin; it is RDBMS specific. 
H2 has a "SYSTEM TABLE" called USERS seemingly, so no chance you could use that. https://h2database.com/html/systemtables.html
I can use SchemaTool on a table called USER without issue. 
Testcases are defined by https://www.datanucleus.org/documentation/problem_reporting.html#jpa

**Comment by sdyura** [comment]
should i report this bug to https://github.com/datanucleus/datanucleus-rdbms then?
i am 100% sure the name "users" is allowed in mysql, and used to work totally fine in DN3, and with DN5 i get this error:

     [java] javax.persistence.RollbackException: Transaction failed to commit
     [java] 	at org.datanucleus.api.jpa.JPAEntityTransaction.commit(JPAEntityTransaction.java:113)
     [java] 	at org.datanucleus.samples.jpa.tutorial.Main.main(Main.java:68)
     [java] Caused by: javax.persistence.PersistenceException: Error(s) were found while auto-creating/validating the datastore for classes. The errors are printed in the log, and are attached to this exception.
     [java] 	at org.datanucleus.api.jpa.NucleusJPAHelper.getJPAExceptionForNucleusException(NucleusJPAHelper.java:316)
     [java] 	at org.datanucleus.api.jpa.JPAEntityTransaction.commit(JPAEntityTransaction.java:107)
     [java] 	... 1 more
     [java] Caused by: java.sql.SQLSyntaxErrorException: Table 'nucleus.users' doesn't exist
     [java] 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
     [java] 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
     [java] 	at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:764)
     [java] 	at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:648)
     [java] 	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:194)
     [java] 	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:194)
     [java] 	at org.datanucleus.store.rdbms.table.AbstractTable.executeDdlStatement(AbstractTable.java:860)
     [java] 	at org.datanucleus.store.rdbms.table.AbstractTable.executeDdlStatementList(AbstractTable.java:811)
     [java] 	at org.datanucleus.store.rdbms.table.TableImpl.validateColumns(TableImpl.java:256)
     [java] 	at org.datanucleus.store.rdbms.RDBMSStoreManager$ClassAdder.performTablesValidation(RDBMSStoreManager.java:3437)
     [java] 	at org.datanucleus.store.rdbms.RDBMSStoreManager$ClassAdder.run(RDBMSStoreManager.java:2946)
     [java] 	at org.datanucleus.store.rdbms.AbstractSchemaTransaction.execute(AbstractSchemaTransaction.java:118)
     [java] 	at org.datanucleus.store.rdbms.RDBMSStoreManager.manageClasses(RDBMSStoreManager.java:1643)
     [java] 	at org.datanucleus.store.rdbms.RDBMSStoreManager.getDatastoreClass(RDBMSStoreManager.java:646)
     [java] 	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.getDatastoreClass(RDBMSPersistenceHandler.java:88)
     [java] 	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.insertObject(RDBMSPersistenceHandler.java:123)
     [java] 	at org.datanucleus.state.StateManagerImpl.internalMakePersistent(StateManagerImpl.java:4569)
     [java] 	at org.datanucleus.state.StateManagerImpl.flush(StateManagerImpl.java:5769)
     [java] 	at org.datanucleus.store.types.SCOUtils.validateObjectForWriting(SCOUtils.java:1238)
     [java] 	at org.datanucleus.store.rdbms.scostore.ElementContainerStore.validateElementForWriting(ElementContainerStore.java:290)
     [java] 	at org.datanucleus.store.rdbms.scostore.JoinSetStore.addAll(JoinSetStore.java:339)
     [java] 	at org.datanucleus.store.rdbms.mapping.java.CollectionMapping.postInsert(CollectionMapping.java:157)
     [java] 	at org.datanucleus.store.rdbms.request.InsertRequest.execute(InsertRequest.java:591)
     [java] 	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.insertObjectInTable(RDBMSPersistenceHandler.java:162)
     [java] 	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.insertObject(RDBMSPersistenceHandler.java:138)
     [java] 	at org.datanucleus.state.StateManagerImpl.internalMakePersistent(StateManagerImpl.java:4569)
     [java] 	at org.datanucleus.state.StateManagerImpl.flush(StateManagerImpl.java:5769)
     [java] 	at org.datanucleus.flush.FlushOrdered.execute(FlushOrdered.java:106)
     [java] 	at org.datanucleus.ExecutionContextImpl.flushInternal(ExecutionContextImpl.java:4068)
     [java] 	at org.datanucleus.ExecutionContextImpl.flush(ExecutionContextImpl.java:4014)
     [java] 	at org.datanucleus.ExecutionContextImpl.preCommit(ExecutionContextImpl.java:4189)
     [java] 	at org.datanucleus.ExecutionContextImpl.transactionPreCommit(ExecutionContextImpl.java:729)
     [java] 	at org.datanucleus.TransactionImpl.internalPreCommit(TransactionImpl.java:397)
     [java] 	at org.datanucleus.TransactionImpl.commit(TransactionImpl.java:287)
     [java] 	at org.datanucleus.api.jpa.JPAEntityTransaction.commit(JPAEntityTransaction.java:99)

**Comment by andyjefferson** [comment]
As already said, it works for me with "USER" (on H2), and if I specify the catalog/schema (for the reason mentioned) then it also works with "USERS" (on H2). No reason to think that will be any different with other databases. What "happened" in v3 is of no interest to me ... 10 years ago!

Your stack trace is not using SchemaTool so nothing much to say. That is why there is a defined testcase format, and it is expected that people do some investigation why they get what they get.
