### ISSUE TITLE
backend.Set.removeAll() broken in 6.0.1

### ISSUE THREAD

**Issue by aley2003** [datanucleus/datanucleus-core#481]
Since commit fcf4f5f6157e726686cebe85d86518b097bae97f  
"removeAll cleanup - only need "contained" in queue update case" from 21. Feb 2022 
org.datanucleus.store.types.wrappers.backed.Set.removeAll(java.util.Collection<?> elements) 
(sometimes) does no longer delete the elements from the data store.
removeAll() does not longer add remove operations to the queue, becaues the Collection _contained_ is filled after _delegate.removeAll(elements)_ was called, so _contained_ will be empty all the time.
To fix removeAll() the commit has to be reverted or a better solution to avoid collecting contained elements to often is needed.

**Comment by aley2003** [comment]
The following implementation of Set.removeAll fixes this issue.
I have problems with me GitHub keys so i could not create a pull request.
[Set.removeAll.java.zip](https://github.com/datanucleus/datanucleus-core/files/9682369/Set.removeAll.java.zip)

**Comment by andyjefferson** [comment]
`Collection<E> contained = new java.util.HashSet<>();`
so you create a HashSet always, whether its needed or not. No thanks.

You could try just moving `delegate.removeAll(elements);` to later (with released DN codebase). But there is no test provided either so only you can work out if that fixes your problem.

**Comment by aley2003** [comment]
I didn't want to change too much to avoid overlooked side effects.
The creation of the empty HashSet could be avoided by moving the call of the constructor inside the if.
I have not done this because of the danger of a NullPointerException in case of later refactorings.
It is not as elegant but I would say correctness beats needed resources/performance.

Moving the _delegate.removeAll(elements);_ down would need a change in the stucture of the function I and do not know in which cases the call of the function is really needed. I guess in all cases so there multiple calls of _delegate.removeAll(elements);_ would be needed.

Is there any existing test case for a store types wrapper? 
I do not know how to create a org.datanucleus.store.types.wrappers.backed.Set with backingStore != null and ownerSM != null for a test.

**Comment by andyjefferson** [comment]
Kindly provide a test that demonstrates so0mething

**Comment by aley2003** [comment]
This problem is fixed in release 6.0.2
