### ISSUE TITLE
Bulk fetch of empty collections can cause `ClassCastException` when calling setter with a different collection implementation

### ISSUE THREAD

**Issue by nscuro** [datanucleus/datanucleus-core#500]
## Bug Report

As of DN 6.0.4 (https://github.com/datanucleus/datanucleus-rdbms/commit/7fc3a65c96eb8913c3e2fe5745c668c57328e0e1), collections that were bulk-fetched, but are empty, are initialized with the default implementation of their respective `Collection` interface. For example, a field of type `List` will be initialized with an empty `ArrayList`.

When overriding this default value with a collection that is equal in content, but uses a different `Collection` implementation (e.g. when both collections are empty), a `ClassCastException` occurs.

A reproducer can be found here:

https://github.com/nscuro/datanucleus-test-jdo/blob/bulk-fetch-regression/src/test/java/org/datanucleus/test/SimpleTest.java

Example Stacktrace produced by the reproducer:

```text
java.lang.ClassCastException: class java.util.LinkedList cannot be cast to class java.util.ArrayList (java.util.LinkedList and java.util.ArrayList are in module java.base of loader 'bootstrap')

	at org.datanucleus.store.types.wrappers.ArrayList.setValue(ArrayList.java:48)
	at org.datanucleus.state.StateManagerImpl.setObjectField(StateManagerImpl.java:3193)
	at mydomain.model.Person.dnSetproperties(Person.java)
	at mydomain.model.Person.setProperties(Person.java:47)
	at org.datanucleus.test.SimpleTest.testSimple(SimpleTest.java:56)
```

**Comment by andyjefferson** [comment]
Note that this is nothing to do with the fix referred to as such, but more due to the handling of setXXX calls via the enhancement contract and the StateManager.
