### ISSUE TITLE
Improve Clarity of datanucleus Exception Messages in Integration Scenarios

### ISSUE THREAD

**Issue by sercanCyberVision** [datanucleus/datanucleus-core#513]
Between Hive MetaStore version 3.1.3 and MySQL integration, the following `datanucleus` dependencies are utilized:
```
    <datanucleus-api-jdo.version>4.2.4</datanucleus-api-jdo.version>
    <datanucleus-core.version>4.1.17</datanucleus-core.version>
    <datanucleus-rdbms.version>4.1.19</datanucleus-rdbms.version>
    <datanucleus-jdo.version>3.2.0-m3</datanucleus-jdo.version>
```

When the `datanucleus` layer encounters an exception while interacting with MySQL, the error message tends to be vague and does not clearly indicate the root cause. For instance, in scenarios where MySQL is set as `read_only`, the `datanucleus` returns a generic root cause [message](https://github.com/datanucleus/datanucleus-core/blob/725824a05db208316e86b7e58e4555ce54395052/src/main/resources/org/datanucleus/Localisation.properties#L806):
```
Root cause: org.datanucleus.exceptions.NucleusUserException: Could not create "increment"/"table" value-generation container `SEQUENCE_TABLE` since autoCreate flags do not allow it.
```
If MySQL is not set as `read_only`, everything works as expected. But, the root cause message suggests that the issue caused by `autoCreate` flag.

**Comment by chrisco484** [comment]
Datanucleus 4.x is now 2 major versions (and many years) behind the latest 6.x so any changes will likely only be made in version 6.x.

**Comment by andyjefferson** [comment]
No way of seeing this problem, hence closing. Kindly follow the test case standard on the website (to use the latest version of code) so that people can see
