### ISSUE TITLE
Reading embedded non trivial data type runs into endless loop

### ISSUE THREAD

**Issue by gpunkt2016** [datanucleus/datanucleus-core#519]
Hi all,
we have a persisted object with an embedded date type value. After the object was written to the database we try to read it from the database creating a new PersistenceManagerFactory with the same properties as it was written. With the older environment of java 8 and datanucleus 5 all went right. After we have changed it to open-jdk 11 and datanucleus 6 the reading process runs into an endless loop. 
Find a testcase for the issue described under https://github.com/gpunkt2016/test-jdo , please. 
The attachement contains the complete log for the testcase. To find the loop you could search for the string "replaced by a SCO wrapper".

[datanucleus.log](https://github.com/user-attachments/files/17775423/datanucleus.log)

Many thanks for any hints.

Regards
gpunkt

**Comment by andyjefferson** [comment]
Should work using the change just committed.
