### ISSUE TITLE
Endless loop in AbstractNamingFactory.getColumnName() when called for embedded collection

### ISSUE THREAD

**Issue by nonstans** [datanucleus/datanucleus-core#97]
In org.datanucleus.store.schema.naming.AbstractNamingFactory.getColumnName(List<AbstractMemberMetaData>, int) I stuck in an endless loop. It occurs when calling getExtend() on class SoftwareDO provided in example.zip. 
This class has 2 embedded lists of GlobalFeedbackSelectors ("inputs" and "outputs"). Each of them contains an embedded object "source" of type W7XVirtualReference, which again has embedded fields.

The problem in the getColumnName method is that the array embMmds (line 185) is not null, but of length == 0, which results in an endless loop, because checked never gets true. The problem occurs when trying to determine the name of the columns input and output. The desired information isn't found in embmd.getMemberMetaData() but in rootMmd. 
I provided a fix for the method (lines 186-192, 200), which works for me. I suggest to rename the flag "manipulated" so that it fits in your world.

I made no tests for arrays or maps. Maybe this is already addressed by #30 ?
I ran my tests agains DN 5.0.0-m5.
[example.zip](https://github.com/datanucleus/datanucleus-core/files/313433/example.zip)
[AbstractNamingFactory.zip](https://github.com/datanucleus/datanucleus-core/files/313444/AbstractNamingFactory.zip)

.

**Comment by andyjefferson** [comment]
Thanks for the report, but some zip file is not a way to show a fix. 
Please use a GitHub PULL REQUEST. That way it shows what lines of code are changed

**Comment by nonstans** [comment]
Thank you for the advise...this was my first try with git and github. The endless loop is gone.
